databases:
  - name: api_drf_task
    databaseName: api_drf_task
    user: api_drf_task

services:
  - type: web
    name: api_drf_task
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn api_drf_task.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api_drf_task
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
