# Generated by Django 4.2.4 on 2023-08-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descriptionTask',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='isDone',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
