# Generated by Django 4.2.4 on 2023-08-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0002_task_descriptiontask_task_isdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
