# Generated by Django 4.2.4 on 2023-08-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0003_alter_task_isdone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='descriptionTask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='isDone',
        ),
    ]
